### ISSUE TITLE
[WIP] My experiences with acid-store

### ISSUE THREAD

**Issue by Byron** [lostatc/acid-store#1]
First of all, thanks a lot for making this crate! I am very interested in trying it out, and am currently experimenting with it. This issue is a platform for communicating my findings and experiences in the hopes to provide you with yet another usecase which might one day be supported.

### Motivation

I am building a mining platform for crates.io which consists of 3 stages:

* **fetch changes**
  *  The first fetch will always be all crate versions thus far, which is ~215000. Then it fetches changes again in intervals, and won't see more than say 100 new crate versions per day
  * Receiving the first batch of 215000 is incredibly fast, as it basically serializes all of the them from memory into the database.
  * it also stores crate objects which are merely the available versions per crate. There are ~36000 of them.
* **processing**
  * This stage runs in intervals and will iterate all crate versions to see if there are unfinished tasks. Tasks are currently downloading the crate and extracting it to gather meta-data. Tasks are stored as small objects that serve as markers. For two tasks currently available, it would store numCrates times two small task types.
   * Each task produces a task result to store the outcome of the computation.
  * more tasks are planned
* **reporting**
 * runs in intervals, and traverses all crate versions and generates one or more HTML files for displaying intelligence obtained from the data we gathered thus far.
 * to avoid generating a page needlessly, it marks the presence of a page in the database （even though right now it marks them with symlinks)

For the current implementation, we are talking about 6 * 215000 + 36000 objects, that are read often, and usually written in small batches, excluding the first run when we see all ~215k crate versions at once.

Eventually I would like to run 'criner' on a Raspberry Pi with 512MB of memory for all tasks that don't require running cargo/rustc. Thus I would prefer a DB which trades of speed for lower and predictable memory consumption. Sled clearly is optimized for speed, which is great, but it's something I can't even pay for on my current hardware as it simply consumes too much memory when during migrations and when there are too many objects.

### The current database

The database of choice is [Sled](https://github.com/spacejam/sled), but I ran into the following issues that make me seek out an alternative.

* [high memory usage when using many tiny objects](https://github.com/spacejam/sled/issues/986)
* [performance issues when using criner](https://github.com/spacejam/sled/issues/976)

Despite sled generally being lightning fast, it costs a lot of memory to support it. Now I run into problems where the memory consumption is disproportional and so high that I feel uncomfortable proceeding with it. Database sizes tend to be large, even though that isn't my primary concern. It's the concern of not being able to interact with the data anymore that one spent days producing. For instance, migrating from one version to another once took 50GB in memory (and it's a wonder my MBPro did not die trying, but completed the herculean task).

#### Migration

* When transferring all data in Sled to an ObjectRepository with SQLite backend, while doing a commit only at the end of all object write, the processing got slower and slower the more objects were uncommitted. I will try committing every 1000 objects to see if the performance slowdown is caused by the commit mechanism, or the underlying database. Edit: Committing every 1000 or 100 objects avoids the slowdown.
  * When looking at IO statistics at the end of writing ~210k objects into SQLite, it tooks about 6GB of writes to produce a 115MB file.
<img width="736" alt="Screenshot 2020-02-27 at 13 24 46" src="https://user-images.githubusercontent.com/63622/75417689-a2269900-596c-11ea-972d-53b3f8bc9c83.png">
  
   * SQLite files are small! This seems great, especially after seeing sled easily take 10GB

* When using an ObjectRepository with a DirectoryBackend, the removal of obsolete objects was prohibitively slow. The runtime was dominated by IO calls.
* It's surprisingly hard [to 'open or create' a database](https://github.com/crates-io/criner/blob/c9b79b6a116a1b42ded9e5060dc13376c8d92f2e/criner/src/migration.rs#L18).
* I would _love_ to disable encryption and compression with cargo features, they pull in around 100 additional crates to compile.

**Comment by Byron** [comment]
I hope you find this information useful.

`acid-store` has incredibly interesting properties, and I feel that with encryption, compression and deduplication along with an sqlite container, it could be an amazing storage format for sensitive data, and more.

Of course, all that comes at a cost so for my particular usecase, it's too slow and would block `criner` on IO all the time. Recent tests show that even naive usage of `sqlite` is orders of magnitudes faster.

**Comment by lostatc** [comment]
Thank you so much for this feedback @Byron! Sorry it took me so long to reply—things have been kinda hectic lately and I apparently had email notification disabled (whoops). I really appreciate the thorough testing.

Performance is something I plan to work on. I'll try and do the following:
- Look into why performance degrades with many uncommitted objects
- Try to reduce the number of writes where possible
- Improve performance cleaning up obsolete objects (I have some ideas here)
- Add an option to *open or create* a data store (or at least check whether a data store exists)
- Gate encryption/compression behind cargo features (you're right; that's a lot of dependencies)

Thanks again!
