### ISSUE TITLE
wasm wasi?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [lostatc/acid-store#8]

**Comment by dzmitry-lahoda** [comment]
donation button?

**Comment by lostatc** [comment]
Sorry for the *exceedingly* late reply.

WASM/WASI support isn't something I have planned, mostly because I have zero experience with WASM.

And no donation button either; donations really aren't necessary. 🙂

**Comment by dzmitry-lahoda** [comment]
you can do 2 things.

1. compile to wasm-xxx-yyy target with no_std enabled. you will see compilation failures.  read the docs about `core` and `alloc` crates and this https://docs.rust-embedded.org/embedonomicon/smallest-no-std.html .  example of no_std and wasm https://github.com/CosmWasm/cw-storage-plus/pull/26/files

2. i am not expert in wasi, BUT https://github.com/bytecodealliance/cap-std  
2.1 it is from people behind WASM standard
2.2. And, cap-std is a foundation for the [WASI](https://github.com/WebAssembly/WASI/) implementation in [Wasmtime](https://wasmtime.dev/), providing sandboxing and support for Linux, macOS, Windows, and more.
2.3 cap-std also has another role, within WASI, because cap-std's filesystem APIs closely follow WASI's sandboxing APIs. In WASI, cap-std becomes a very thin layer, thinner than libstd's filesystem APIs because it doesn't need extra code to handle absolute path
2.4. so if you use that lib, likely compile to WASI flag will work out of box

WASM/WASI grows very fast, it outpased as i see other trends and it lacks DB stuff

**Comment by lostatc** [comment]
Thanks for the advice! I might look into it when I have some time.
