### ISSUE TITLE
OpenMode::Create mode is ignored when opening a local directory

### ISSUE THREAD

**Issue by Klaim** [lostatc/acid-store#9]
Hi, this is a bug report.

# Summary

We want to open a repository if it exists, create it if not, which is the purpose of `OpenMode::Create`.
However, when doing so, at least when using `FileRepo` and `DirectoryConfig`, the repo opening fails at the second opening because the implementation attempted to re-create the directory, which is not was was requested.

# How To Reproduce

Repro case (main.rs):
```rust
use std::path::{ PathBuf };
use acid_store::repo::{ file::FileRepo, OpenOptions, OpenMode, };
use acid_store::store::{ DirectoryConfig };

fn main() {
    use std::env;
    let args: Vec<String> = env::args().collect();

    let config = DirectoryConfig{
        path: PathBuf::from(&args[1])
    };

    let _repo : FileRepo = OpenOptions::new()
        .mode(OpenMode::Create) // This seems to be ignored!
        .open(&config)
        .unwrap();

    let stdin = std::io::stdin();
    loop {
        let mut input = String::new();
        stdin.read_line(&mut input).expect("failed to read input");
        if input == "exit\n" {
            break;
        }
    }
}
```

Compile and run it twice:
```
cargo run /tmp/myrepo
cargo run /tmp/myrepo
```

## Observed

Failure on any run with the same directory argument after the first call with that directory: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Store(File exists (os error 17))', src/main.rs:17:10
```

## Expected

No error, no attempt at creating the directory when we use `OpenMode::Create` and successful opening of the repository.

# Notes

In `open-options.rs` we can locate this call which shows that the mode is handled after attempting to access the store, instead of in the store.
```rust
 let mut store = config.open()?; // HERE

        match self.mode {
            OpenMode::Open => self.open_repo(store),
            OpenMode::Create => { // HANDLED HERE
```

Going into the call to `config.open()` then leads to this code:
```rust
fn open(&self) -> crate::Result<Self::Store> {
        // Create the blocks directory in the data store.
        create_dir_all(&self.path)
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?;
        create_dir(self.path.join(STORE_DIRECTORY))
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?; // FAILS HERE
        create_dir(self.path.join(STAGING_DIRECTORY))
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?;
        create_dir(self.path.join(type_path(BlockType::Data)))
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?;
        create_dir(self.path.join(type_path(BlockType::Lock)))
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?;
        create_dir(self.path.join(type_path(BlockType::Header)))
            .map_err(|error| crate::Error::Store(anyhow::Error::from(error)))?;
 ```
 
 We can see that the option is not handled at the right level and directory creation is "forced" systematically.
 
 We did not attempt to see if the same issue appear with other kinds of stores. We intend to check with S3.

**Comment by lostatc** [comment]
Hi @Klaim!

Thanks for the incredibly detailed bug report! This issue should be fixed, and I don't believe it occurs with other kinds of stores. I just published `v0.11.1`.
